# Site settings
title: Lillebælt Bouldering
description: Bouldering fællesskab i Middelfart og omegn. Klatring for alle niveauer, events og træning.
baseurl: "/lillebaeltboulderingWebsite" # the subpath of your site, e.g. /blog
url: "https://kinkio.github.io" # Update this with your GitHub Pages URL

# Environment variables (populated during build)
env:
  GOOGLE_SCRIPT_URL: "" # Will be populated from GitHub secretsWill be populated from GitHub secrets

# Build settings
markdown: kramdown
# remote_theme: pages-themes/architect@v0.2.0  # Commented out to use custom styles

# Sass configuration
sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections (if needed for future content)
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/